apiVersion: v1
kind: Secret
metadata:
  name: {{ include "studentsystemgo.fullname" . }}-app
  labels:
    {{- include "studentsystemgo.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ required "env.DB_PASSWORD is required" .Values.env.DB_PASSWORD | quote }}
  jwt-secret: {{ required "env.JWT_SECRET is required" .Values.env.JWT_SECRET | quote }}