apiVersion: v1
kind: Service
metadata:
  name: mysql-primary
  labels:
    {{- include "studentsystemgo.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql-primary
spec:
  clusterIP: None        # ← THIS is what makes it "headless"
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
  selector:
    app.kubernetes.io/name: studentsystemgo
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mysql-primary