apiVersion: v1
kind: Secret
metadata:
  name: {{ include "studentsystemgo.fullname" . }}-rabbitmq
  labels:
    {{- include "studentsystemgo.labels" . | nindent 4 }}
type: Opaque
stringData:
  user: {{ .Values.rabbitmq.defaultUser | quote }}
  password: {{ required "rabbitmq.defaultPass is required" .Values.rabbitmq.defaultPass | quote }}
  # Pre-computed URL for the app to consume
  url: {{ printf "amqp://%s:%s@rabbitmq:5672/" .Values.rabbitmq.defaultUser (.Values.rabbitmq.defaultPass | default "") | quote }}