apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    {{- include "studentsystemgo.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  clusterIP: None
  ports:
    - port: 5672
      targetPort: 5672
      name: amqp
    - port: 15672
      targetPort: 15672
      name: management
  selector:
    app.kubernetes.io/name: studentsystemgo
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: rabbitmq