apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "studentsystemgo.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  clusterIP: None
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app.kubernetes.io/name: studentsystemgo
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis